//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ictshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
        }
    
        public int Masp { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string Tensp { get; set; }
        [Display(Name = "Giá tiền")]
        public Nullable<decimal> Giatien { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> Soluong { get; set; }
        [Display(Name = "Mô tả")]
        public string Mota { get; set; }
        [Display(Name = "Thẻ sim")]
        public Nullable<int> Thesim { get; set; }
        [Display(Name = "Bộ nhớ trong")]
        public Nullable<int> Bonhotrong { get; set; }
        [Display(Name = "Sản phẩm mới")]
        public Nullable<bool> Sanphammoi { get; set; }
        [Display(Name = "Bộ nhớ ram")]
        public Nullable<int> Ram { get; set; }
        [Display(Name = "Ảnh bìa")]
        public string Anhbia { get; set; }
        public Nullable<int> Mahang { get; set; }
        public Nullable<int> Mahdh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual Hangsanxuat Hangsanxuat { get; set; }
        public virtual Hedieuhanh Hedieuhanh { get; set; }
    }
}
