// <auto-generated />
namespace Ictshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddThanhtien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddThanhtien));
        
        string IMigrationMetadata.Id
        {
            get { return "202107271655114_AddThanhtien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
